site_name: EmptyFlow.SciterAPI
site_author: 'Roman Vladimirov'
docs_dir: docs/
repo_name: 'EmptyFlow/SciterAPI'
repo_url: 'https://github.com/EmptyFlow/SciterAPI'
nav:
  - Home: index.md
  - Creating Project: creatingproject.md
  - Load HTML and show window: loadingandrun.md
  - Adding Event handlers: eventhandlers.md
  - Register file protocols: fileprotocols.md
  - Find element and change content: fileelement.md
  - Using Values: createvalue.md